services:
  # ---------------- core service database ----------------
  core-db:
    image: postgres:latest
    container_name: hyperlinker-core-db
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_pass
      POSTGRES_DB: core_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U core_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5445:5432"            # exposed only for local dev
    volumes:
      - core-data:/var/lib/postgresql/data

  # ---------------- analytics service database ----------------
  analytics-db:
    image: postgres:latest
    container_name: hyperlinker-analytics-db
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: analytics_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5446:5432"
    volumes:
      - analytics-data:/var/lib/postgresql/data

  # ---------------- infra shared by multiple services ----------------
  redis:
    image: redis:8.0.2
    container_name: hyperlinker-redis
    ports: ["6379:6379"]

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: hyperlinker-kafka
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "INTERNAL://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    ports: ["9092:9092"]

volumes:
  core-data:
  analytics-data:
