FROM gradle:8.14.2-jdk21 AS build
WORKDIR /workspace
COPY . .
RUN gradle :core:bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine
ARG JARP=/workspace/core/build/libs
COPY --from=build ${JARP}/core-*.jar /app/core.jar
EXPOSE 8082
ENTRYPOINT ["java","-jar","/app/core.jar"]