server:
  port: 8080

spring:
  application:
    name: api-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
  # API is stateless; no database required here
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: api-service

  security:
    oauth2:
      resourceserver:
        jwt:
          # JWKS endpoint or file, override per-environment
          jwk-set-uri: ${JWK_SET_URI:https://auth.github.dimitryivaniuta.com/.well-known/jwks.json}

logging:
  level:
    root: INFO
    com.github.dimitryivaniuta.api: DEBUG

# Enable transactional behavior in controllers/services
spring:
  transaction:
    default-timeout: 30s
    rollback-on-commit-failure: true

# Swagger / OpenAPI UI custom path
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html