server:
  port: 8081

spring:
  application:
    name: edge-service
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: 2s
  # No datasource here; edge is stateless for link resolution
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    com.github.dimitryivaniuta.edge: DEBUG